# Generated by Django 4.0.1 on 2022-02-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_tasklist_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='managers',
        ),
    ]
